## Even Fibonacci numbers
#Problem 2

=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
=end

class ProjectEuler

  def solution

    limit = 19
    val = 0
    j = 0
    fibonacci = [1]
    
    for i in (1...limit)
        val = fibonacci[j] + fibonacci[i-2]
        j = j +1
      
      fibonacci.push(val)
    end

  puts fibonacci.max
  end
  
end

object = ProjectEuler.new()
object.solution
